- files/rundeck_version
The previously used code only worked on platforms that have dpkg. Because this uses puppet's RAL, it should run on any platform.
Be aware; either the version is returned, or when not installed, the string "absent" is returned.
> This should work on any OS.

- README.md
There are a few mistakes I noticed while reading this doc; these commits correct them:
* Travis build status image linked to former opentable repo.
* "Setup" had an odd trailing backtick
* "Private Classes" didn't render as a heading
> Fix minor README formatting issues

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- templates/apitoken.aclpolicy.erb
Hello,
I needed to fiddle with the API acl settings and noticed that the module uses a hardwired template. I changed the template, so it's similar to the existing regular acl template. I made some modifications to enable 'filter' clauses (`match`, `equals`) in the rules. With these changes a semantically equivalent file is generated as before. 
My use case was to allow a specific user **runAs** privileges on certain jobs.
> Add option to configure API acls

- spec/classes/config/global/auth_spec.rb
- templates/realm.properties.erb
Previously it was not possible to create a realm.properties with more than the admin user. Only the admin user would be created with a valid syntax. 
This pull request adds support for an array of users. Roles don't have to be provided as they're optional. Furthermore, the order of a user's properties is not relevant anymore. A line breaking issue and a comma issue have also been fixed. 
Everything comes with tests :)
> Multiple auth users

- README.md
There was some kind of syntax problem making it unclear what public and what private classes are available.
> Syntax problem mixed public and private classes

- templates/log4j.properties.erb
Without this patch, the access log file has no newline, so the log is one
very long line. (And the contentType and userAgent are missing.)
(I'm unclear about whether this originated with the template or if it
was from the file distributed with rundeck itself; at any rate, it seems
to be correct upstream).
> Fix clipped log format without newline (issue #57)

- manifests/config.pp
- manifests/init.pp
- spec/classes/config_spec.rb
With $jvm_args only accessible in rundeck::params, it is not possible
override the values there. It is necessary add to the JVM parameters to
configure rundeckd to listen on a different port than the default and
bind to a specific IP address, both of which are preferred when setting
up Apache httpd to proxy (I want to change the port to one that SELinux
allows httpd to connect to by default, such as 8008); it is also
necessary to add "-Drundeck.jetty.connector.forwarded=true" to enable it
to use the X-Forwarded-* HTTP headers.
I am also just replacing the default from rundeck::params, rather than
merging or concatenating, as I can easily imagine wanting to use
different memory parameters than the ones hard-coded there.
> Add support for setting jvm_args (issue #59)

- spec/classes/rundeck_spec.rb
- templates/_auth_ldap.erb
For sites using RFC 2307 posixGroup for roles, the *roleMemberAttribute* does not work, because the posixGroup *memberUid* attributes are usernames and not DNs; the *roleUsernameMemberAttribute* is for this.
> Enable "roleUsernameMemberAttribute" for LDAP auth (issue #62)

- spec/classes/rundeck_spec.rb
This commit creates an rspec context into which the spec tests for my fixes for issues #61 and #62 will go. I was attempting to make it possible to merge for fixes without conflicts, but I was not wholly successful. At any rate, this is a pre-requisite for the LDAP pull requests #64 and #65.
Note that even with this, #64 and #65 will have conflicts that will have to be managed manually. If you'd like, I can submit another PR that merges both, although it should be fairly obvious how to resolve the conflict.
> Add context for merging potentially conflicting LDAP tests (issues #61 & #62)

- manifests/params.pp
- spec/acceptance/rundeck_spec.rb
- spec/classes/rundeck_spec.rb
As I documented in issue #48, recent versions of Rundeck require Java 1.7 or they crash on startup:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dtolabs/rundeck/RunServer : Unsupported major.minor version 51.0
...
```
I have only updated the RHEL section; I don't have a Debian host handy to find the OpenJDK versions available and anyway Rundeck itself is locked at an older version for Debian (possibly for this very reason). OpenJDK 1.7.0 is available at least as far back as RHEL/CentOS 5.
(This is a re-creation of PR #49, rebased to the current upstream master and based on a topic branch, instead of my master.)
> Require Java 1.7 for RHEL, per Rundeck reqs (#48)

- manifests/install.pp
- rundeck service is not restarted after upgraded in CentOS
> bugfix/#43 - rundeck service is not restarted after upgraded in CentOS

- manifests/params.pp
The storage rule was missing, so the admin user was not able to create a storage record
> Fixed admin.aclpolicy params

- spec/classes/rundeck_spec.rb
- templates/_auth_ldap.erb
This commit allows an "url" parameter to be used for `providerURL` instead of building the URL with "server" and "port"; this allows specifying "ldaps" for protocol (issue #61) and makes it more reusable with my existing hiera data.
> Allow an "url" parameter for LDAP connection (issue #61)

- manifests/init.pp
- rundeck service need be restarted if config is changed.
> bugfix/#81 - service need be restarted if config is changed.

- manifests/install.pp
- manifests/params.pp
- spec/classes/install_spec.rb
The rundeck package will create a default user and group of 'rundeck' if
a non-default user and group is specified by this module then we want to
make sure that they are created properly, that the rundeck defaults are
removed and that all directories have the correct permissions.
> Fix for #72 - bug with non-default user and group

- .fixtures.yml
- README.md
- manifests/config/plugin.pp
- manifests/install.pp
- metadata.json
- spec/classes/install_spec.rb
- spec/defines/config/plugin_spec.rb
refactored plugin defined type to remove the if/then logic and set defaults when the parameter is declared.  Added the 'ensure' parameter to the defined type to allow removal of an installed plugin. moved the plugin directory resource to the config class to allow multiple plugin definitions.
changed from an exec to download the plugin to using the maestrodev/wget module.  This does add a dependency on that module.
> Plugin refactor

- manifests/params.pp
- spec/acceptance/rundeck_spec.rb
- spec/classes/config/global/framework_spec.rb
- spec/classes/config/global/project_spec.rb
- spec/classes/config_spec.rb
- spec/defines/config/resource_source_spec.rb
This was not caught by the systems tests either which is what was shown
in issue #91.
This commit fixes the default back to $RDECK_BASE/projects and updates
the tests to catch these in the future.
> Fix the projects directory default in framework.properies.

- manifests/config.pp
- manifests/config/aclpolicyfile.pp
- spec/defines/config/aclpolicyfile_spec.rb
Updated the parameter defaults to fixed values not inherited from the
root rundeck class because it avoids any issues if the define is used on
it's own (not sure why you would do that) and also allows me to write a
test for the default case of the properties.dir setting.
Due to the above change I also update the config.pp file accordingly to
pass-through the remaining parameters.
> Fix for #100 deep merging issue with aclpolicyfile

- manifests/params.pp
The package is fetched over simple http for debian based distribution.
As the site `https://dl.bintray.com/rundeck/rundeck-deb` now support tls, I changed the source parameter to use https by default.
> fetching packages over tls instead of clear test

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- templates/profile.erb
The java system properties server.web.context is needed to modify the context path. That's usefull behind a proxy.
So I propose to add this argument
Sources : http://rundeck.org/docs/administration/installation.html#system-properties
Note: I corrected the style in the profile.erb
> Add server.web.context argument

- lib/puppet/parser/functions/validate_rd_policy.rb
- lib/puppet/util/rundeck_acl.rb
- manifests/init.pp
- manifests/params.pp
- spec/classes/rundeck_spec.rb
- spec/defines/config/aclpolicyfile_spec.rb
- spec/functions/validate_rd_policy/application_spec.rb
- spec/functions/validate_rd_policy/project_spec.rb
- spec/functions/validate_rd_policy/signature_spec.rb
- spec/spec_helper.rb
- templates/aclpolicy.erb
Given the complexities of writing rundeck's acl policies it has come up
again and again where passing incorrect data into the hash can cause
puppet to generate an invalid policy file.
The point of this change is to restructure the hash so that it better
repsents the structure of the acl policy itself and to provide a parser
function for the policy hash so that the data can be validated.
> A new function to validate the acl policies

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- templates/profile.erb
Default it will look to the environment settings JAVA_HOME.
We install java by just unpacking a packages in a directory.
So it would be nice if this can be set optionally.
> Set java_home directory

- manifests/config.pp
- manifests/params.pp
- templates/_auth_ad.erb
- templates/_auth_ldap.erb
- templates/jaas-auth.conf.erb
- templates/realm.properties.erb
Before applying this, please see https://github.com/puppet-community/puppet-rundeck/issues/94 and https://github.com/puppet-community/puppet-rundeck/issues/96 as these fixes were merged to this feature branch (JettyCombinedLdap). 
-------
Since Rundeck 2.5 there is a new very useful feature:  LDAP "shared authentication credentials". 
see http://rundeck.org/docs/administration/authenticating-users.html#ldap for more details.
This pull request provides puppet's implementation of that feature 
to activate this feature $auth_types should be assigned as 
- ldap_shared
**or**
- active_directory_shared
That means that rundeck will authenticate user with LDAP (or AD) and will perform authorization with FileLoginModule (realm file) to assign provided roles
- …
> Jetty combined ldap

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
This allows for rundeck::projects to be specified like so, in YAML:
```
rundeck::projects:
'Infrastructure': {}
'Applications': {}
'NOC': {}
```
This creates the projects.
> Add rundeck::projects to specify projects in your rundeck instance

- README.md
Documentation fix for option auth_type, should be auth_types. Available options provided as well
> Documentation fix for option auth_type

- manifests/config/resource_source.pp
Add `aws-ec2` as resource_source to support [Rundeck EC2 Nodes Plugin](https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin).
> (#112) Add `aws-ec2` as resource_source to support Rundeck EC2 Nodes Plugin

- manifests/config.pp
- spec/classes/config/global/ssl_spec.rb
- spec/classes/config_spec.rb
- templates/profile.erb
Hello:
I noticed that when ssl isn't enabled, that running rd-jobs from the cli produces ssl warnings:
````
[root@rundeck rundeck]# rd-jobs list -p Infrastructure
Error: Error making server request to http://rundeck:4440: Error occurred while trying to authenticate to server: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
````
This PR only calls the SSL bits when it's enabled.
> Only include ssl bits when ssl is enabled

- templates/facts.rb.erb
Fixes the following issue which will crash puppetdb due to the fact returning malformed data.
https://github.com/puppet-community/puppet-rundeck/issues/132
> (#132) Fixing bad syntax on rundeck_version fact

- README.md
- manifests/config.pp
- manifests/config/global/web.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config/global/web_spec.rb
To change the `security-role` currently one must edit `web.xml` directly, and reapply the change upon upgrade, as that file is version-specific and must be kept in sync with the application. I have opened an issue with rundeck to make that configurable via something in `/etc/rundeck` (rundeck/rundeck#1261), but unless or until that is resolved, I need to be able to manage it.
This creates a `rundeck::config::global::web` class with this as the sole parameter which is also added and passed through `rundeck` and `rundeck::config`. I chose to use an *augeas* resource because the file is XML and needs to be replaced outside of Puppet, so a template would not work. Many people have an aversion to augeas because it can get complicated; I find that for certain classes of problems it can be …
> Add class to manage security-role in web.xml

- manifests/install.pp
So java management was already removed from this module, but we still have a java dependency inside the deb package. As a result deployment can fall in case of custom java deployment.
Example:
```
Error: /Stage[main]/Rundeck::Install/Exec[install rundeck package]/returns: change from notrun to 0 failed: /usr/bin/dpkg --force-confold -i /tmp/rundeck-2.5.1-1-GA.deb returned 1 instead of one of [0]
```
```
(Reading database ... 92055 files and directories currently installed.)
Preparing to unpack /tmp/rundeck-2.5.1-1-GA.deb ...
Unpacking rundeck (2.5.1) over (2.5.1) ...
dpkg: dependency problems prevent configuration of rundeck:
rundeck depends on java7-runtime | java7-runtime-headless | java8-runtime | java8-runtime-headless; however:
Package java7-runtime is not installed.
Package …
```
> remove java dependency from deb

- spec/classes/config/global/aclpolicyfile_spec.rb
- templates/aclpolicy.erb
Validates against RD 2.6's rd-acl validate.
@liamjbennett
> Validate ACLs against rd-acl recommendations

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
Using `realm_template`, `realm.properties` could be customized. By default, `rundeck/realm.properties.erb` is used.
> (#110) Add support for customizing realm.properties

- manifests/config.pp
- manifests/config/global/rundeck_config.pp
- manifests/init.pp
- manifests/params.pp
There are customizations to `rundeck-config` that I would like to do. Using the `rdeck_config_template`, I could specify a template for it. By default, it would use `rundeck/rundeck-config.erb`.
PS: My first contribution to puppet-rundeck, please comment on my diff.
> (#108) Add support for customizing rundeck-config

- README.md
- manifests/config.pp
- manifests/config/global/rundeck_config.pp
- manifests/init.pp
- manifests/params.pp
- templates/rundeck-config.erb
This feature allows to modify path of the key storage directory. (The Key Storage container allows storing public keys, private keys, and passwords)
related discussion: https://groups.google.com/forum/#!topic/rundeck-discuss/fzrQ26USTPU
> key storage non-default dir path support

- manifests/params.pp
- templates/log4j.properties.erb
Addresses https://github.com/puppet-community/puppet-rundeck/issues/85
Added option in log4j.properties.erb to disable h2 logging, as this workaround for https://github.com/rundeck/rundeck/issues/1175 still seems to be required
> disable H2 database logging in log4j.properties

- manifests/config.pp
- spec/classes/config/global/auth_spec.rb
- templates/_auth_ad.erb
- templates/_auth_ldap.erb
added ldap login module if ldap in $auth_types (was previously being defaulted to null for cases when both 'file' and 'ldap' were both in $auth_types)
> should contain JettyCachingLdapLoginModule and be sufficient

- manifests/config/resource_source.pp
https://forge.puppetlabs.com/puppetlabs/inifile
> value
> Optional. Supplies a value for the specified setting. Valid options: a string. Default value: undefined.
> value field in ini_setting is now always a string

- manifests/config.pp
- manifests/config/file_keystore.pp
- manifests/config/global/file_keystore.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config/global/file_keystore_spec.rb
- spec/classes/config/global/rundeck_config_spec.rb
- templates/file_keystorage_meta.erb
Added mechanism to automate provisioning of password and public keys for file-based keystorage in rundeck::config::global::file_keystore, with key data provided via hiera.
Example of key data hash:
```
{
$key1 => {
$value        => 'secret',
$path         => 'myproject/passwords',
$data_type    => 'password',
$content_type => 'application/x-rundeck-data-password', },
$key2 => {
$value        => 'ssh-rsa Th1sIsn0tRe@alLyAnRSAk3y',
$path         => 'myproject/pubkeys',
$data_type    => 'public-key',
$content_type => 'application/pgp-keys', },
}
```
> added provisioning of file-based keystores via hiera

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
Following https://github.com/voxpupuli/puppet-rundeck/pull/109,  I've created a patch but this time for customizing `profile`.
By default, it will still use `rundeck/profile.erb`
> Add support for customizing profile

- manifests/config.pp
- manifests/config/global/rundeck_config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.erb
Since v.2.5 Rundeck supports  preauthenticated mode http://rundeck.org/docs/administration/authenticating-users.html#preauthenticated-mode
This patch adds the necessary bits to configure it.
> Support preauthenticated mode config

- manifests/install.pp
As you may know, I'm trying to configure Rundeck to use [preauthenticated-mode](http://rundeck.org/docs/administration/authenticating-users.html#preauthenticated-mode).
One of the issues I'm facing now is that I need to be sure that all Rundeck's directories are owned by the `$user` and `$group` rundeck has been installed as. The current code does not ensure it.
This patch is meant to fix this issue.
I set 0640 for everything since this is what it was applied on /etc/rundeck but I'm not against changing it to 644 (default) or any other.
> Ensure rundeck directories are owned by $user and $group

- manifests/config/global/file_keystore.pp
- manifests/config/project.pp
- manifests/params.pp
- spec/classes/config/global/file_keystore_spec.rb
- spec/classes/config/global/scm_properties_spec.rb
- spec/defines/config/project_spec.rb
- templates/scm-import.properties.erb
* added management of scm-import.properties files via hiera, which is used by Rundeck SCM for project jobs; does not (yet) execute the 'git clone' which actually retrieves the jobs onto the Rundeck server
* fixed some ambiguity in tests for file_keystore_spec.rb
* https://github.com/dalisch/puppet-rundeck/blob/manage_scm_import_properties/spec/classes/config/global/scm_properties_spec.rb
```
rundeck::projects:
my_project:
scm_import_properties:
scm.import.config.useFilePattern: true
scm.import.config.strictHostKeyChecking: 'no'
scm.import.config.filePattern: 'proect_1/*'
scm.import.config.url: 'https\://github.com/rundeck/rundeck-jobs-test.git'
scm.import.config.format: yaml
scm.import.config.dir: /var/lib/rundeck/projects/my_project/scm
scm.import.config.pathTemplate: …
```
> Added management of scm-import.properties

- manifests/config/global/web.pp
When I opened the PR for configuring preauthenticated mode (https://github.com/voxpupuli/puppet-rundeck/pull/175), I forgot this:
[From the rundeck docs:](http://rundeck.org/docs/administration/authenticating-users.html#preauthenticated-mode)
`The file WEB-INF/web.xml inside the war contents must be modified to remove the <auth-constraint> element. This disables the behavior which causes the Container to trigger its authentication mechanism when a user browses to a Rundeck page requiring authorizaton.`
This patch should take of it.
> Remove auth-constraint from web.xml if preauthenticated mode enabled

- .rubocop.yml
- .travis.yml
- CONTRIBUTING.md
- Gemfile
- spec/spec_helper.rb
See https://github.com/voxpupuli/modulesync_config/pull/93
This commit updates the module to our latest modulesync configuration.
> Pin rake to avoid rubocop/rake 11 incompatibility

- manifests/config.pp
- manifests/install.pp
* refactored file resource management by utilizing resource default for file permissions and ownership
* removed 'recurse' property on all files in $rdeck_base and subdirs
* resubmission of [PR#202](https://github.com/voxpupuli/puppet-rundeck/pull/202) now that the master branch is happy again
* https://github.com/voxpupuli/puppet-rundeck/issues/196
> refactored file permissions management

- templates/aclpolicy.erb
The aclpolicy.erb template does not indent nodenames in project config
output:
```
for: [...]
node:
- match:
nodename: 'mynode.example.com'
allow: '*'
```
should be 
```
for: [...]
node:
- match:
nodename: 'mynode.example.com'
allow: '*'
```
> Fix indentation for nodename property in aclpolicy template

- manifests/config.pp
- manifests/config/global/rundeck_config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config/global/gui_config_spec.rb
- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.erb
Added hash for rundeck.gui.* properties to be added to rundeck-config.groovy, to facilitate [Rundeck GUI customization](http://rundeck.org/docs/administration/gui-customization.html).
* new parameter $gui_config is a hash that is intended to contain all of the rundeck.gui.* properties; values are added to the end of rundeck-config.groovy
https://travis-ci.org/dalisch/puppet-rundeck/builds/118297584
> Add Rundeck GUI customization properties

- README.md
This one-line change is an assertion that Rundeck has been installed and
is functional on CentOS 7.  Since CentOS 7 is already included in the
supported platforms, this change is merely to keep documentation up to
date.
> Add CentOS 7 to tested platforms

- README.md
Without this change, there is no example for users who wish to use an
existing, external database.  Here we update the README to reflect what
it takes to get the configuration on disk in a state that will enable an
external MySQL database for key and project storage.
> Add note and example about using an external MySQL DB

- manifests/params.pp
- spec/classes/config/global/aclpolicyfile_spec.rb
Without this change, storage is omited from the default policy for
admin, leaving the administrative user unable to modify storage items,
like 'keys/'.
This change amends the default policy to allow the admin user full
control over storage.
> Amend default policy for full storage control

- manifests/config.pp
- manifests/config/project.pp
- manifests/init.pp
- manifests/params.pp
- templates/krb5.conf.erb
- templates/profile.erb
- Added Kerberos realm config management
- Corrected framework properties hash merge in project.pp
- Removed validation on the node executor plugin (only validates three plugin names, other plugins such as the winrm-overthere plugin will cause validation to fail)
>  - Added ability to specify node executor settings

- manifests/config/project.pp
- manifests/params.pp
- spec/classes/config/global/scm_spec.rb
- spec/defines/config/project_spec.rb
- templates/scm-export.properties.erb
* similar to existing scm_import_properties, new hash parameter scm_export_properties added in `rundeck::config::project` when it is desired to pre-specify the SCM configuration for exporting Rundeck jobs
* properties used to populate scm-export.properties via `scm-export.properties.erb` template
> Automate configuration of SCM export properties in a project

- manifests/config/file_keystore.pp
- spec/classes/config/global/file_keystore_spec.rb
Trying to add a custom file_keystorage_dir I found out this error:
Error: Failed to apply catalog: Validation of Exec[create _public key path] failed: 'mkdir -m 775 -p /var/lib/rundeck/var/storage/content/keys/; chown -R rundeck:rundeck /var/lib/rundeck/var/storage/content/keys/' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppet/modules/rundeck/manifests/config/file_keystore.pp:77
I fix this adding provider => shell to the exec at /etc/puppet/modules/rundeck/manifests/config/file_keystore.pp:77
> Simple fix qualify command

- manifests/config/global/project.pp
Project.organization previously had project.description, and vice-versa.
> Correcting values of project.organization and projection.description

- templates/aclpolicy.erb
Simple fix on aclpolicy.erb template.
The template produce a wrong structure:
resource:
- equals:
kind: job
- equals:
allow: [create] # allow create jobs
The correct one should be:
resource:
- equals:
kind: job
allow: [create] # allow create jobs
> Simple fix aclpolicy.erb template

- manifests/init.pp
- manifests/params.pp
- manifests/service.pp
We are running Rundeck in Preauthenticated Mode with a different Servlet Container (Tomcat).
Because of this, we need to ensure that `rundeckd` service is not running (stopped) in favor of the tomcat service, which is the one actually service launching rundeck.
This patch makes this possible without changing the default behavior.
> Add param to configure service state

- templates/rundeck-config.erb
The template shall not reference keys in the mail config hash
that might not be there.
As discussed IRL, I'll take over this PR from @ak0ska  :)
> Do not write non-existent mail configuration

- manifests/config/file_keystore.pp
- spec/classes/config/global/file_keystore_spec.rb
* re-introduced management of base $file_keystorage_dir (it was originally working after this PR: https://github.com/voxpupuli/puppet-rundeck/pull/172).  Added test to prevent future occurrences.
> fixed management of $file_keystore_dir

- examples/demo_install_el7.pp
Simple example for demo purposes howto install Rundeck
on EL7 (RedHat, CentOS).
> Example manifest to demo-install Rundeck on EL7

- CHANGELOG.md
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/install_spec.rb
> feature: set user and group id because of NFS Share

- manifests/config.pp
The 'rd_autidlevel' parameter was missing from the parameter list in config.pp. This meant that the template did not have access to it and thus resulting in a missing value for the log4j configuration (e.g. ', audit').
> Add missing 'rd_auditlevel' parameter to config.pp

- .fixtures.yml
- README.md
- manifests/config.pp
- manifests/config/global/framework.pp
- manifests/config/global/ssl.pp
- manifests/init.pp
- manifests/params.pp
- metadata.json
- spec/acceptance/rundeck_spec.rb
- spec/classes/config/global/auth_spec.rb
- spec/classes/config/global/framework_spec.rb
- spec/classes/config/global/gui_config_spec.rb
- spec/classes/config_spec.rb
- spec/classes/rundeck_spec.rb
- templates/profile.erb
- feature: generate Keytool files
- fix: profile.erb due to "RDECK_SSL_OPTS"
> Feature: Keytool

- metadata.json
There's nothing wrong with using puppet/archive 1.1.2 (current latest
release).
https://github.com/voxpupuli/puppet-archive/releases/tag/v1.1.2
> Update puppet/archive dependency

- templates/aclpolicy.erb
> add: tags to fix aclpolicy

- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
to disable the ssh key file management. This defaults to true, which is
the current behavior. This is meant as a fix for issue #259.
> This adds a boolean class parameter to the rundeck class to allow people

- templates/aclpolicy.erb
as defined in the rundeck documentation, there are default node resource properties. i would like to add those to the aclpolicy template to ensure proper indentation
http://rundeck.org/docs/administration/access-control-policy.html#node-resource-properties
> Add missing node resource properties to acltemplate

- .fixtures.yml
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- metadata.json
- spec/classes/config/global/aclpolicyfile_spec.rb
- spec/classes/config/global/auth_spec.rb
- spec/classes/config/global/file_keystore_spec.rb
- spec/classes/config/global/framework_spec.rb
- spec/classes/config/global/project_spec.rb
- spec/classes/config/global/rundeck_config_spec.rb
- spec/classes/config/global/scm_spec.rb
- spec/classes/config_spec.rb
- spec/classes/install_spec.rb
- spec/classes/rundeck_spec.rb
- spec/classes/service_spec.rb
- spec/defines/config/plugin_spec.rb
- spec/defines/config/project_spec.rb
- spec/defines/config/resource_source_spec.rb
- spec/defines/config/securityroles_spec.rb
- spec/spec_helper_acceptance.rb
rundeck packages are available from bintray ( https://bintray.com/rundeck/rundeck-deb )
obviously we want to use apt to install rundeck on debian-based hosts
im available on freenode#voxpupuli if you have questions
(see PR #285 , thanks to @grafjo for explaining rspec to me:-) )
> install rundeck from apt for osfamily debian

- metadata.json
We currently only run automated tests against Puppet 3 latest and
therefore cannot guarantee that this module works as is expected with
earlier Puppet 3 versions
Also set pltraining/dirtree dependency version range
> Set puppet minimum version_requirement to 3.8.7

- templates/_auth_ldap.erb
added userPasswordAttribute to ldap config template, like the ad config template( see https://github.com/voxpupuli/puppet-rundeck/blob/5e2f06e10ae5c1a576ac52b23231b3790e3179aa/templates/_auth_ad.erb#L27 ) as my ldap setup required it as well.
> added userPasswordAttribute to ldap config, like AD config

- manifests/params.pp
The default rundeck api acl config, has an additional section describing job acls, which are required when using rundeck from jenkins for instance.
> Adding missing api config settings.

- manifests/config/resource_source.pp
If using multiple AWS EC2 resource sources a duplicate declaration raises following the fact there's no project notion in the resource name.
> Fix ini settings for aws-ec2 resource source

- manifests/params.pp
- metadata.json
- spec/classes/rundeck_spec.rb
* if `$::serialnumber` fact is empty, use a UUID generated from the FQDN of the system
* bump stdlib requirement
* Adds spec to test
Replaces #275
> Change to use `fqdn_uuid()` function

- manifests/install.pp
- spec/classes/install_spec.rb
`Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Illegal Class name in class reference. A TypeReference['Apt::Update']-Type cannot be used where a String is expected at /etc/puppetlabs/code/environments/mgmt/modules/rundeck/manifests/install.pp:66:129`
The current code, breaks on  Puppet5, this pull request remedies the error above
> Update for use with puppet5

- .sync.yml
- .travis.yml
- Gemfile
- README.md
- examples/ldap_shared.pp
- manifests/config.pp
- manifests/config/plugin.pp
- manifests/config/project.pp
- manifests/config/resource_source.pp
- manifests/init.pp
- manifests/install.pp
- metadata.json
- spec/acceptance/rundeck_spec.rb
- spec/classes/rundeck_spec.rb
- spec/spec_helper_acceptance.rb
This will add the acceptance tests back to the Travis matrix, simplifies them, and also resolves an idempotency issue on certain platforms.
I believe this will also fix the issue that was causing modulesync to fail.
I switched apt to be a soft dep per https://docs.puppet.com/puppet/5.1/style_guide.html#dependencies and also listed Java as a dependency (the acceptance tests install puppetlabs/java but I don't think the setup requirements mentioned it).
> Fix acceptance tests and run in Travis. Resolve idempotency issue

- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.erb
Currently the template for the rundeck config accepts params for the following:
`rundeck.security.useHMacRequestTokens`
`rundeck.security.apiCookieAccess.enabled`
Added the rest of the options to the security hash for the rundeck config.  
Added to support the following:
`rundeck.api.tokens.duration.max`
`rundeck.security.csrf.referer.filterMethod`
`rundeck.security.csrf.referer.allowApi`
`rundeck.security.csrf.referer.requireHttps`
Updated tests to cover the conditionals in the template.
> Add the rest of the options to the security hash for the rundeck config.

- README.md
- metadata.json
Not sure if we consider dropping official support breaking (since it should still work).
@bastelfreak what do you think about pulling this in before release?
> Drop support for RedHat 5 and Ubuntu 12, Update README and metadata.

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
Allow users to use their custom templates for generating the log4j.properties file
> Add support to customize log4j.properties file

- manifests/config/project.pp
The existing regex is too restrictive.
Plugins allow other values.  eg I want to use
'com.batix.rundeck.plugins.AnsibleFileCopier'
> Allow all strings for file_copier_provider

- manifests/config/aclpolicyfile.pp
- manifests/config/file_keystore.pp
- manifests/config/plugin.pp
- manifests/config/project.pp
- manifests/config/resource_source.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config/global/framework_spec.rb
- spec/classes/config/global/web_spec.rb
- spec/classes/install_spec.rb
- spec/defines/config/resource_source_spec.rb
- types/loglevel.pp
- types/sourcetype.pp
This removes almost all of the `validate_` calls (there's a custom function specific to this module that will probably need to stay, and not sure what to do about `validate_absolute_path($projects_dir)` in `manifests/config/resource_source.pp`, since it's not a param (I think it can probably just be removed, but leaving just in case).
May still need some review / fixes
> Breaking: Switch to Puppet Data Types, switch to integers

- manifests/params.pp
- spec/classes/config/global/auth_spec.rb
- templates/_auth_ad.erb
- templates/_auth_ldap.erb
I'm using rolePrefix to map Active Directory groups to Rundeck roles.  This has been working in production AD and LDAP environments.
> add rolePrefix attribute to LDAP and Active Directory authentication

- manifests/config/global/framework.pp
- spec/classes/config/global/framework_spec.rb
I think this should accomplish a fix to #303, and somewhat improves test coverage, though there's room for more improvement.
The reason the existing tests worked is that the stubbed in data matches rspec-puppet-facts's $fqdn fact (h/t to Johnson Earls for that gem, as well as for a couple other useful improvements to these changes). This should handle the case where the user overrides `framework.server.hostname` a little more magically than before (though perhaps not the case where the user wishes to override `framework.server.url` directly?)
> Don't change framework.server.{port,url}, use framework.server.hostname rather than fqdn (#303)

- metadata.json
Looks like it's not breaking anything. As far as I can see it is only used in the rundeck::config::plugin class.
> changed requirements for puppet-archive to allow version 2.x

- README.md
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/install_spec.rb
This:
- Adds the GPG check for rpm packages (though with a default source at the same repo the package is from
- Adds the ability to control key ID / keyserver (apt), key source (rpm), and repo sources, with the existing defaults in params (the repo is still named bintray-rundeck, though, even though someone could theoretically specify a different one)
- Removes the unused package_source parameter
- Improves test coverage slightly
Because of the last point, we can probably label this as breaking, though the param seems to already have been unused.
> Use gpgkey for rpm (#205), remove package_source param, add new params for repos

- spec/acceptance/rundeck_spec.rb
There's probably room for a lot more testing (would be cool to even create an API token and make a test call to it).
This is a start to doing a bit more testing, by creating a project and verifying some basics about it.
I also tried verifying that it's listening on the right port, but I don't want to add a sleep, and the port isn't listening yet at the point where the test runs.
> Create a simple project with default values in the acceptance test

- README.md
- manifests/config.pp
- manifests/config/global/ssl.pp
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/config_spec.rb
- spec/classes/install_spec.rb
This introduces new params `manage_user` and `manage_group`, disabled by default (as the package should create the Rundeck user already).
There may still be problems with some corner cases; setting alternate usernames or trying to change the username with different UIDs (or change the numeric UID for the Rundeck user while Rundeck is running) may cause errors and / or idempotency issues -- but I think it's at least a big improvement over the previous logic.
This also simplifies the logic around user creation a bit now that there are data types.
It moves some items that used to be handled in the install class to the config class, and removes direct notifies of the service from config class, since the config class as a whole notifies `rundeck::service`
> Breaking: Don't manage user / group by default

- metadata.json
$default_resource_dir is set to '/' by default.
stdlib versions earlier than 4.21.0 do not accept this for the
Stdlib::Absolutepath data type
Fixes #362
> Bump stdlib to 4.21.0

- manifests/params.pp
- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.erb
Hi folk!
This PR adds the ability to set the rest of the newer preauthenticated options (added via https://github.com/rundeck/rundeck/pull/1883 in rundeck a few months ago).  It should be harmless to older versions of rundeck as they will simply ignore the settings they don't know to look for.
> Added support for additional preauth options

- manifests/install.pp
This fixes an issue where initial setup on RedHat systems can require two puppet runs.
> Ensure repos are set up before installing rundeck-config

- manifests/install.pp
The rundeck user and group should probably be declared as system user/group since it's meant to be a service account/group.
Fixes #380
> Make rundeck user/group system user/group

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config_spec.rb
manage_home will determine if the home directory is managed.
Usefull for us, because we needed to bind mount the homedir.
This meant that the mount and directory needed to exist
before executing the rundeck module.
> Creating the home dir is now optional

- manifests/config/resource_source.pp
- spec/defines/config/resource_source_spec.rb
> Rework of PR #313 with actual master branch

- manifests/config.pp
This fixes the default project description and organization.
Currently the `rundeck` class pulls in defaults for `projects_description` and `projects_organization` from `rundeck::params`, then `rundeck::config` attempts to pull them out of `rundeck` using the wrong name.  The result is that when calling `rundeck` and providing `projects_description` and/or `projects_organization`, those values are not used, and the defaults from `rundeck::params` are used instead.
This simply fixes the names that `rundeck::config` is using to pull the the description and organization from `rundeck`.
n/a
> Fix default project attribute names

- manifests/params.pp
- spec/acceptance/rundeck_spec.rb
This is the latest 2.X version. 3.X got recently released, but requires
some changes to our module. To keep it working for now, we pin it to 2.9.4.
> pin rundeck to version 2.11.5

- manifests/config.pp
- manifests/params.pp
- spec/acceptance/rundeck_spec.rb
- spec/classes/config/global/rundeck_config_spec.rb
- spec/classes/config/global/web_spec.rb
- spec/defines/config/securityroles_spec.rb
- templates/rundeck-config.erb
Quickwin to get rundeck 3.x running without error on:
- no more existant WEB-INF/web.xml 
- log4j.properties file location in rundeck-config.groovy
-> https://rundeck.org/news/2018/07/27/rundeck-3.0.0.html
> Add support for rundeck 3.x

- .sync.yml
- lib/facter/rundeck_version.rb
- spec/facter/fact_rundeck_version_spec.rb
- spec/spec_helper.rb
This PR fixes rebase needed of PR #392 
Added another fact : rundeck_commitid
This PR fixes rebase needed of PR #392 
Added another fact : rundeck_commitid
> Fix PR #392 + added rundeck_commitid fact

- README.md
- examples/demo_install_el7.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/rundeck_spec.rb
This PR generates the server UUID from the serial number rather than just using the serial number directly, since serial numbers are rarely valid RFC 4122 UUIDs.
With cluster mode enabled, Rundeck requires that `rundeck.server.uuid` be a valid RFC 4122 UUID ([Rundeck source](https://github.com/rundeck/rundeck/blob/d4d1b189728c82953fae1c6d39b5665f817e3549/rundeckapp/grails-app/conf/BootStrap.groovy#L183-L197)).
n/a
> Turn serialnumber into UUID

- manifests/config/resource_source.pp
This adds the `assumeRoleArn` parameter to resource sources that was added in the [ec2 nodes plugin](https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/pull/40).
> Add assume_role_arn for aws-ec2 resource source

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
Allow setting different default file mode
Currently, the module sets the default file permission to 0640 in the config class. This change allows to set it to an arbitrary value.
n/a
> Allow setting different default file mode

- README.md
- manifests/config.pp
- manifests/config/global/rundeck_config.pp
- manifests/init.pp
- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.erb
This changeset adds a new option to the module so it's possible to configure a storage encryption plugin. Example:
```yaml
rundeck::config::storage_encrypt_config:
type: 'jasypt-encryption'
path: 'keys'
config.encryptionType: 'basic'
config.password: 'verysecure'
```
https://docs.rundeck.com/docs/administration/configuration/plugins/bundled-plugins.html#jasypt-encryption-plugin
> Add option storage_encrypt_config

- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.erb
As described in [rundeck/docs issue 44](https://github.com/rundeck/docs/issues/44), and fixed in [this commit](https://github.com/rundeck/docs/commit/b3cea42e45edf11c70f10a3f34b72bb748bc60e9),
the threadCount configuration key changed from `quartz.props.threadPool.threadCount` to `quartz.threadPool.threadCount`
Replaces the threadCount configuration key with the correct one (as indicated by a change in rundeck documentation)
Fixes #435
> 435 - Update threadCount configuration key

- manifests/config.pp
- manifests/init.pp
- spec/classes/config_spec.rb
- spec/fixtures/files/override.template
Allows the user to specify a different override template as the one that comes with the module.
In some situations, it's just enough to set parameters in the override file that goes into /etc/sysconfig/rundeckd or /etc/default/rundeck  to configure rundeck, leaving the profile (/etc/rundeck/profile) untouched and managed by the packager.
This PR just provides the possibility to specify it and it defaults to the previous behavior for any user of this module.
Signed-off-by: Jose Castro Leon <jose.castro.leon@cern.ch>
> Add possibility to override profile template

- spec/classes/config_spec.rb
Signed-off-by: Jose Castro Leon <jose.castro.leon@cern.ch>
In the MR regarding the override_template parameter, it seems that I introduced an issue that our local rubocop CI founds.
This is just to avoid such issue and prevent CI jobs to fail.
RuboCop failed!
Running RuboCop...
Inspecting 29 files
...C.........................
Offenses:
spec/classes/config_spec.rb:67:61: C: Layout/SpaceInsideBlockBraces: Space missing inside }.
let(:params) { { rdeck_override_template: template }}
^
spec/classes/config_spec.rb:69:52: C: Layout/SpaceInsideBlockBraces: Space missing inside }.
it { is_expected.to contain_file(overrides)}
^
29 files inspected, 2 offenses detected
> Fix rubocop issues with override_template MR

- templates/realm.properties.erb
This changeset fix issue when @auth_config['file']['auth_users'] hash is empty, a colon added in realm.properties file when it shouldn't.
Fix also wrong indentation.
Fixes #459
> (#459) prevent colon added in realm.properties when auth_users hash is empty

- metadata.json
- spec/spec_helper_acceptance.rb
also contains:
* https://github.com/voxpupuli/puppet-rundeck/pull/464
* https://github.com/voxpupuli/puppet-rundeck/pull/463
* https://github.com/voxpupuli/puppet-rundeck/pull/465
* https://github.com/voxpupuli/puppet-rundeck/pull/466
* https://github.com/voxpupuli/puppet-rundeck/pull/467
> puppetlabs/apt: Allow 8.x

- manifests/config/project.pp
- metadata.json
Change the (now deprecated) create_ini_settings function to its namespaced alternative inifile::create_ini_settings and increase the minimal supported version of inifile dependency, to the first version where inifile::create_ini_settings was introduced. 
Fixes #496
> Inisettings resolve deprecation: use namespaced `create_ini_settings` function

- README.md
- REFERENCE.md
- manifests/config.pp
- manifests/config/global/rundeck_config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/config/global/rundeck_config_spec.rb
- templates/rundeck-config.epp
The key storage type parameter limits the key storage entries to one.
It would be better to simplify this to one configurable hash.
Also remove vault specific parameters to limit breaking changes when vault-storage plugin updates config on their side.
Update docs as well.
> Update key storage parameters and update documentation

- data/Debian.yaml
- spec/acceptance/rundeck_spec.rb
- spec/classes/install_spec.rb
This PR will fix the debian gpg validation and will improve the rundeck install spec file
> Fix debian gpg validation and improve rundeck::install spec file

- README.md
- REFERENCE.md
- data/Debian.yaml
- data/RedHat.yaml
- files/rd_project_diff.sh
- manifests/cli.pp
- manifests/config/project.pp
- manifests/init.pp
- metadata.json
- spec/classes/cli_spec.rb
- spec/classes/config/ssl_spec.rb
- spec/classes/config_spec.rb
- spec/classes/install_spec.rb
- spec/classes/rundeck_spec.rb
- spec/classes/service_spec.rb
- spec/defines/config/aclpolicyfile_spec.rb
- spec/defines/config/project_spec.rb
- types/project.pp
This introduces the rundeck cli as a seperate class and als add a define to create and manage projects
Fixes #449
Fixes #181
Fixes #67
> Add rundeck cli and project management

- REFERENCE.md
- files/rd_job_diff.sh
- manifests/cli.pp
- manifests/config/project.pp
- manifests/init.pp
- spec/classes/cli_spec.rb
- spec/defines/config/project_spec.rb
- types/job.pp
- types/project.pp
This PR adds a way to manage jobs through cli and adds a parameter to notify cli connection check
Fixes #33
Fixes #458
> Add Job management

- manifests/config/project.pp
This PR will remove the command option -r for the job creation.
This is because the option -r removes uuid when uploading the job file, which will cause an infinite diff loop with the original file.
> Remove command opt which caused an infinite loop

- REFERENCE.md
- manifests/config/project.pp
- manifests/init.pp
- spec/defines/config/project_spec.rb
- templates/log4j2.properties.epp
- templates/rundeck-config.properties.epp
- types/job.pp
This PR will add more log levels, fix the job loop and add ensure to job type.
> Add more log levels and fix job loop

- manifests/config/project.pp
- spec/classes/cli_spec.rb
- spec/defines/config/project_spec.rb
To avoid duplicate job resources, the project name is included in the job exec
> Avoid duplicate resources by including project name

- spec/classes/config/jaas_auth_spec.rb
- templates/jaas-loginmodule.conf.epp
We had some issues with open files and after some investigation we came to a conclusion that is was opening too many
/etc/rundeck/realm.properties files and was an issue apparently https://github.com/rundeck/rundeck/issues/7096
So this MR fixes this.
> Fix jaas-loginmodule template

- manifests/config.pp
- spec/classes/config_spec.rb
Correct `framework.logs.dir` path.
Fixes #547
> fix: `framework.logs.dir` path

- REFERENCE.md
- manifests/init.pp
- templates/rundeck-config.properties.epp
Remove a hard coded setting and introduce a new parameter that allows a broader range of grails settings.
Fixes #552
> Allow setting Grails configuration in `rundeck-config.properties`
