metadata.json
make license field spdx compatible (https://spdx.org/licenses/)
=> spdx compatible license

files/rundeck_version
instead of yum and dpkg-query instead of `dpkg|awk`.
=> Like #46, fix puppet/facter #45, but w/rpm

templates/rundeck-config.erb
Inside /etc/rundeck/rundeck-config.groovy / grails {} object the error "unexpected token: default @ ..." was
triggered
=> Extracted grails.mail.default.from as property again

manifests/init.pp
Fixed document typo on auth_types param.
=> Fix little typo in docs.

manifests/config/resource_source.pp, spec/defines/config/resource_source_spec.rb
=> Fix #73 - Wrong user & group variables for project dir in resource_source

manifests/config/project.pp, manifests/config/resource_source.pp, spec/defines/config/resource_source_spec.rb
refactored resource source defined type to remove the if/then logic and set defaults when the parameter is declared.  added namevars to resource definitions to allow for multiple resource declarations.
=> Resource source refactor

metadata.json
"Merge branch 'smithtrevor-plugin_refactor'" introduced this issue
=> Fixed invalid metadata.json

templates/_auth_ldap.erb
this will resolve following issue: https://github.com/puppet-community/puppet-rundeck/issues/96
=> fix typo in ldap template

README.md, manifests/config/resource_source.pp
... not really related to pr #34 - but that pr was working on related
code without doing some housekeeping of the documentation.
=> Removed stale resource_source documentation

manifests/params.pp, templates/_auth_pam.erb, templates/jaas-auth.conf.erb
=> Add pam support to authentication

templates/aclpolicy.erb
=> Fix ACL format

metadata.json
Running it on RHEL7 personally just fine.
=> Add RHEL7/CentOS7 to supported OS list

manifests/init.pp
=> removing old example related to java install

README.md, manifests/config.pp, manifests/config/global/web.pp, manifests/init.pp, manifests/params.pp, spec/classes/config/global/web_spec.rb
http://rundeck.org/docs/administration/configuration-file-reference.html#session-timeout
=> add gui session timeout support

manifests/config/project.pp
=> Make ssh_keypath and projects_dir parameters of the project defined type

Gemfile, lib/facter/rundeck_version.rb, templates/aclpolicy.erb
Tag @ak0ska and @liamjbennett 
Please confirm, @ak0ska.
=> Implement #137, adding the rundeck_server parameter

manifests/config/project.pp, manifests/config/resource_source.pp, manifests/init.pp, metadata.json
=> Fixes GH-157

manifests/config.pp, manifests/config/file_keystore.pp, manifests/config/global/rundeck_config.pp, manifests/init.pp, manifests/params.pp, spec/classes/config/global/rundeck_config_spec.rb, templates/rundeck-config.erb
http://rundeck.org/docs/administration/project-setup.html
=> Add ability to specify different project and key storage types

manifests/params.pp, spec/classes/config/global/aclpolicyfile_spec.rb, templates/aclpolicy.erb
Reverts voxpupuli/puppet-rundeck#173
=> Revert "Simplify the acl template"

lib/puppet/parser/functions/validate_rd_policy.rb, manifests/config/global/ssl.pp, manifests/config/resource_source.pp
=> fix(validate_rd_policy) expand relative path for require

manifests/init.pp, templates/log4j.properties.erb
=> Fix audit loglevel 207

spec/classes/config/global/auth_spec.rb, templates/_auth_file.erb
This is a workaround for https://github.com/rundeck/rundeck/issues/1111
=> Update _auth_file.erb (fixes #206)

README.md, manifests/config/project.pp
Various fixes to the README define names and type errors.
=> Documentation fixes

templates/_auth_ldap.erb
Added option 'forceBindingLoginUseRootContextForRoles' to template.
Change cacheDurationMillis as variable due to test/debug.
=> Added option to template : 'forceBindingLoginUseRootContextForRoles'

manifests/config/resource_source.pp, spec/defines/config/resource_source_spec.rb
Please check the following items before submitting a PR -- thank you!
Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).
closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
tries to address multiple issues. Though we prefer one PR per feature/fix,
sometimes that's not feasible. In that case ensure that a single feature/fix
and associated tests and documentation is bundled up in one commit
Optional, but extra points:
reintroduced
- - -
=> added puppet enterprise resource type

.github/ISSUE_TEMPLATE.md, Gemfile, spec/spec_helper.rb
Please check the following items before submitting a PR -- thank you!
Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).
closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
tries to address multiple issues. Though we prefer one PR per feature/fix,
sometimes that's not feasible. In that case ensure that a single feature/fix
and associated tests and documentation is bundled up in one commit
Optional, but extra points:
reintroduced
- - -
=> modulesync 0.8.1

manifests/config.pp, manifests/init.pp
See https://github.com/voxpupuli/puppet-rundeck/issues/248
=> able to change ssl port through parameter

.msync.yml, Gemfile, Rakefile, spec/default_facts.yml, spec/spec_helper.rb
=> modulesync 0.11.0

metadata.json
=> this change allow puppet/archive to live together with camptocamp/archive

manifests/config/resource_source.pp, spec/defines/config/resource_source_spec.rb
See https://github.com/voxpupuli/puppet-rundeck/issues/257
=> puppetdb_ssl_dir is added as parameter

.msync.yml, CHANGELOG.md, metadata.json
=> Modulesync 0.12.8 & Release 3.2.0

metadata.json
=> Fix issue #268.

templates/aclpolicy.erb
Reverts voxpupuli/puppet-rundeck#273
=> Revert "Add missing node resource properties to acltemplate"

.msync.yml, .rubocop.yml, Gemfile, Rakefile
=> modulesync 0.13.3

README.md, manifests/config.pp, manifests/config/global/rundeck_config.pp, manifests/init.pp, manifests/params.pp, spec/classes/config/global/rundeck_config_spec.rb, templates/rundeck-config.erb
More info: https://github.com/voxpupuli/puppet-rundeck/issues/289
=> Add variable quartz_job_threadCount

README.md
when i added the apt repo management for debian installation in an earlier PR (#286), i forgot to update the documentation, so here it is.
=> Update readme apt install

manifests/config/aclpolicyfile.pp, manifests/config/project.pp, manifests/config/resource_source.pp
I _think_ this should resolve the issues with Puppet 5, and seems to work in acceptance test.
Plan to re-add acceptance tests in Travis, and fix some other problems there, in #335
=> Remove 'require' statements on file resources that aren't declared

manifests/config/resource_source.pp, spec/defines/config/resource_source_spec.rb
I think this should fix the problems with tests while (hopefully) eliminating the possible problems introduced in #336
=> Fix tests for file resources in defined type (partially reverts #336)

README.md
=> Fix `database_config` parameter documentation

manifests/init.pp
As discussed with @alexjfisher 
http://rundeck.org/docs/administration/configuring-ssl.html
=> update docs for grails_server_url

.github/CONTRIBUTING.md, .msync.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile, spec/acceptance/nodesets/docker/debian-7.yml, spec/acceptance/nodesets/docker/debian-9.yml, spec/spec_helper.rb
=> modulesync 1.4.0

README.md, manifests/init.pp
Just adding parameter docs for #346
=> add docs for #346

lib/puppetx/rundeck/acl.rb
Can't see any actual use for these
=> remove unneeded 'p' statements

CHANGELOG.md, metadata.json
Major release with multiple backwards-incompatible changes.
=> Release version 5.0.0

manifests/config/resource_source.pp
=> replace validate_string with assert_type

README.md
=> fix log_dir in readme

manifests/config/project.pp, manifests/config/resource_source.pp, manifests/params.pp
=> feat(rundeck): add missing key from resources_source

.msync.yml, .travis.yml, Gemfile, spec/acceptance/rundeck_spec.rb, spec/spec_helper_acceptance.rb
=> modulesync 1.9.6

metadata.json, spec/spec_helper_acceptance.rb
=> allow puppetlabs/apt 5.x, puppetlabs/inifile 2.x, puppetlabs/java_ks 2.x, puppet/archive 3.x

CHANGELOG.md, metadata.json
=> Release 5.4.0

.github/CONTRIBUTING.md, .msync.yml, Gemfile, manifests/config/global/file_keystore.pp, manifests/config/global/rundeck_config.pp, manifests/config/plugin.pp, manifests/config/resource_source.pp, spec/spec_helper.rb
=> modulesync 2.8.0

CHANGELOG.md, README.md, metadata.json
Closes https://github.com/voxpupuli/puppet-rundeck/issues/423
=> Bump version to 6.0.0

README.md, metadata.json
=> drop Ubuntu 14.04 support

.github/CONTRIBUTING.md, .msync.yml, .rubocop.yml, .travis.yml, Dockerfile, Gemfile, Rakefile, manifests/install.pp, manifests/params.pp, spec/classes/config/global/gui_config_spec.rb, spec/classes/config/global/ssl_spec.rb, spec/classes/rundeck_spec.rb, spec/defines/config/plugin_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
=> modulesync 2.12.0

.github/SECURITY.md, .msync.yml, .rubocop.yml, Gemfile, examples/demo_install_el7.pp, examples/ldap_shared.pp, manifests/config.pp, manifests/config/aclpolicyfile.pp, manifests/config/file_keystore.pp, manifests/config/global/file_keystore.pp, manifests/config/global/framework.pp, manifests/config/global/project.pp, manifests/config/global/rundeck_config.pp, manifests/config/global/ssl.pp, manifests/config/global/web.pp, manifests/config/plugin.pp, manifests/config/project.pp, manifests/config/resource_source.pp, manifests/config/securityroles.pp, manifests/init.pp, manifests/install.pp, manifests/params.pp, manifests/service.pp, spec/classes/config/global/auth_spec.rb, spec/classes/config/global/framework_spec.rb, spec/classes/config_spec.rb, spec/classes/rundeck_spec.rb
=> modulesync 3.0.0 & puppet-lint updates

manifests/init.pp, manifests/install.pp, manifests/params.pp, metadata.json, spec/classes/install_spec.rb, spec/spec_helper_acceptance.rb
The rundeck packages seems to have been relocated.  Update this location
to unbreak CI.
also contains:
* https://github.com/voxpupuli/puppet-rundeck/pull/463
* https://github.com/voxpupuli/puppet-rundeck/pull/464
* https://github.com/voxpupuli/puppet-rundeck/pull/465
* https://github.com/voxpupuli/puppet-rundeck/pull/466
* https://github.com/voxpupuli/puppet-rundeck/pull/467
* #468
Fixes #473
Fixes #469
=> Update repo location

metadata.json
also contains https://github.com/voxpupuli/puppet-rundeck/pull/463/
=> puppetlabs/java_ks: Allow 4.x

metadata.json
also contains:
* https://github.com/voxpupuli/puppet-rundeck/pull/464
* https://github.com/voxpupuli/puppet-rundeck/pull/463
* https://github.com/voxpupuli/puppet-rundeck/pull/465
=> puppetlabs/inifile: Allow 5.x

metadata.json, spec/spec_helper_acceptance.rb
also contains:
* https://github.com/voxpupuli/puppet-rundeck/pull/464
* https://github.com/voxpupuli/puppet-rundeck/pull/463
* https://github.com/voxpupuli/puppet-rundeck/pull/465
* https://github.com/voxpupuli/puppet-rundeck/pull/466
=> puppetlabs/java: Allow 7.x

templates/rundeck-config.erb
This adds a dynamic solution for preauthenticated config
=> Add dynamic preauthenticated config

manifests/config.pp, manifests/config/global/framework.pp, manifests/config/global/rundeck_config.pp, manifests/params.pp, templates/_auth_ad.epp, templates/_auth_file.epp, templates/_auth_ldap.epp, templates/_auth_pam.epp, templates/framework.properties.epp, templates/jaas-auth.conf.epp, templates/rundeck-config.epp
This PR add sensitive support for database password and ldap password.
Fixes #482
=> Add sensitive support for db password and ldap password

metadata.json
=> Add OracleLinux/Rocky/AlmaLinux 8 support

metadata.json
=> Add Ubuntu 20.04/22.04 support

lib/puppetx/rundeck/acl.rb, manifests/config/aclpolicyfile.pp, manifests/params.pp, spec/classes/config/global/rundeck_config_spec.rb, spec/defines/config/aclpolicyfile_spec.rb, templates/aclpolicy.erb, templates/realm.properties.epp
=> Fix ACLs rendering when using atributes as filters

CHANGELOG.md, metadata.json
=> Release 8.0.1

metadata.json
Bump version requirement of the dependent modules to allow for their latest version:
- archive
- inifile
- java_ks
Fixes #517
=> Bump version requirements of dependencies to allow for their latest version

REFERENCE.md, types/key_storage_config.pp
removePathPrefix should be an optional parameter for the key storage config
=> Fix key storage config

.fixtures.yml
=> fixtures.yml: remove puppet version contraint

CHANGELOG.md, README.md, metadata.json
=> Release 9.1.0

REFERENCE.md, manifests/config/project.pp, manifests/init.pp, spec/acceptance/hieradata/family/RedHat.yaml, spec/acceptance/rundeck_spec.rb, spec/defines/config/project_spec.rb, templates/rundeck-config.properties.epp, types/auth_config.pp, types/db_config.pp, types/key_storage_config.pp, types/loglevel.pp, types/mail_config.pp, types/project.pp
This will add multiple small code additions and improvements.
Including:
- Add param for project management.
- Update summaries for the different types.
- Update acceptance tests to latest Rundeck at the moment.
- Add param for Rundeck to enable/disable features.
=> Add multiple small code additions and improvements

REFERENCE.md, manifests/config/secret.pp, spec/defines/config/secret_spec.rb
This adds a config define to add secrets to Rundeck key storage.
=> Add code for secrets management in keystorage

REFERENCE.md, files/rd_scm_diff.sh, manifests/cli.pp, manifests/config.pp, manifests/config/project.pp, spec/classes/cli_spec.rb, spec/classes/config_spec.rb, spec/defines/config/project_spec.rb, types/scm.pp
This PR adds a scm_config parameter which allows to configure SCM for a Rundeck project.
Fixes #541
=> Add scm config options to project define

spec/acceptance/rundeck_spec.rb
=> Add Test for latest rundeck v5.7.0-20241021

CHANGELOG.md, metadata.json
=> Release 9.2.0

REFERENCE.md, types/db_config.pp
=> add: dbCreate property
